Repository nonical/hnefatafl, pull requests merged in 2020-05, with the labels that each got.

#32 Allow taking with King
  Assets/Scripts/Logic/TakingLogic.cs
Labels: bug

#35 Restore deleted lines
  Assets/Editor.meta
  Assets/Scenes/SampleScene.unity
  Assets/Textures/Tiles/Materials.meta
  ProjectSettings/ProjectSettings.asset
Labels: bug

#37 Remove unused scene
  Assets/Scenes/Menu.unity
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#42 Add automatic team selection for multiplayer
  Assets/Prefabs/Network.meta
  Assets/Prefabs/Network/NetworkPlayer.prefab
  Assets/Prefabs/Network/NetworkPlayer.prefab.meta
  Assets/Prefabs/Tiles/Border.prefab
  Assets/Prefabs/Tiles/Border.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Logic/InputManagement.cs
  Assets/Scripts/Networking.meta
  Assets/Scripts/Networking/NetworkHandlers.cs
  Assets/Scripts/Networking/NetworkHandlers.cs.meta
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs.meta
  Assets/Scripts/Networking/NetworkMessages.cs
  Assets/Scripts/Networking/NetworkMessages.cs.meta
Labels: enhancement

#46 User IP input
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#45 Remove non-existent script
  Assets/Prefabs/Environment/Latern5.prefab
  Assets/Prefabs/Environment/candlestick.prefab
Labels: bug

#44 Child EventSystem to UI object
  Assets/Scenes/SampleScene.unity
Labels: enhancement

#47 Update version to 0.9.5
  ProjectSettings/ProjectSettings.asset
Labels: documentation, enhancement

#49 Port forwarding for multiplayer
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs
  Assets/Scripts/Networking/PortForwarding.cs
  Assets/Scripts/Networking/PortForwarding.cs.meta
Labels: enhancement

#50 Fix multiplayer UI
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs
  Assets/Scripts/UI/Menus.cs
Labels: bug

#51 Update Unity to version 2019.3.13f1
  Packages/manifest.json
  ProjectSettings/ProjectVersion.txt
Labels: enhancement

#53 New menu appearance
  Assets/Scenes/SampleScene.unity
  Assets/UI/Berry Rotunda.asset
  Assets/UI/LocalButton.prefab
  Assets/UI/LocalButton.prefab.meta
  Assets/UI/Scroll.png
  Assets/UI/Scroll.png.meta
Labels: enhancement

#54 Various fixes
  Assets/Meshes/Environment/Materials.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GameMemory.cs
  Assets/Scripts/Logic/InputManagement.cs
  Assets/Scripts/Logic/TakingLogic.cs
  Assets/Scripts/Logic/WinConditions.cs
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs
  Assets/Scripts/Utility/DebugHelper.cs
  ProjectSettings/ProjectVersion.txt
Labels: bug, enhancement

#55 Add cursor and game icon
  Assets/UI/Icons/Cursor.png
  Assets/UI/Icons/Cursor.png.meta
  Assets/UI/Icons/MainIcon.png
  Assets/UI/Icons/MainIcon.png.meta
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#56 Add UI turn messages
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#57 Rework UI background
  Assets/Materials/Environment/03_Water.mat
  Assets/Materials/Environment/03_Water.mat.meta
  Assets/Materials/Environment/canvas_d.mat
  Assets/Meshes/Environment/05_Glacier.meta
  Assets/Meshes/Environment/05_Glacier/05_Glacier.FBX
  Assets/Meshes/Environment/05_Glacier/05_Glacier.FBX.meta
  Assets/Meshes/Environment/05_Glacier/Map.meta
  Assets/Meshes/Environment/05_Glacier/Map/Glacier Displace.png
  Assets/Meshes/Environment/05_Glacier/Map/Glacier Displace.png.meta
  Assets/Meshes/Environment/05_Glacier/Map/Glacier Displace1.png
  Assets/Meshes/Environment/05_Glacier/Map/Glacier Displace1.png.meta
  Assets/Meshes/Environment/05_Glacier/Material.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #22.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #22.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #25.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #25.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #26.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #26.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #27.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #27.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #28.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #28.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #29.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #29.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/Material #30.mat
  Assets/Meshes/Environment/05_Glacier/Material/Material #30.mat.meta
  Assets/Meshes/Environment/05_Glacier/Material/glacier.mat
  Assets/Meshes/Environment/05_Glacier/Material/glacier.mat.meta
  Assets/Prefabs/Environment/05_Glacier.prefab
  Assets/Prefabs/Environment/05_Glacier.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
  Assets/Scripts/UI/UICamera.cs
  Assets/Shaders/Clouds.shader
  Assets/Shaders/Clouds.shader.meta
  Assets/Shaders/FogInclude.cginc
  Assets/Shaders/FogInclude.cginc.meta
  Assets/Shaders/Terrain.shader
  Assets/Shaders/Terrain.shader.meta
  Assets/Skybox.meta
  Assets/Skybox/Aurora1.mat
  Assets/Skybox/Aurora1.mat.meta
  Assets/Skybox/Clouds_01.tga
  Assets/Skybox/Clouds_01.tga.meta
  Assets/Skybox/Clouds_01_Flow.tga
  Assets/Skybox/Clouds_01_Flow.tga.meta
  Assets/Skybox/Clouds_02.tga
  Assets/Skybox/Clouds_02.tga.meta
  Assets/Skybox/Clouds_Scifi.mat
  Assets/Skybox/Clouds_Scifi.mat.meta
  Assets/Skybox/UpperColor.tga
  Assets/Skybox/UpperColor.tga.meta
  Assets/Skybox/UpperColorGreen.tga
  Assets/Skybox/UpperColorGreen.tga.meta
  Assets/Skybox/UpperColorGreyscale.tga
  Assets/Skybox/UpperColorGreyscale.tga.meta
  Assets/Skybox/Wave_Dist 1.tga
  Assets/Skybox/Wave_Dist 1.tga.meta
  Assets/Skybox/Wave_Dist_2.tga
  Assets/Skybox/Wave_Dist_2.tga.meta
Labels: enhancement

#59 Number of hotfixes for 0.9.6 release
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Logic/InputManagement.cs
  Assets/Scripts/Logic/WinConditions.cs
  Assets/Scripts/UI/Menus.cs
  Assets/UI/Icons/Cursor.png.meta
  Packages/manifest.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#60 Move pieces to crate when they're captured
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Logic/TakingLogic.cs
  Assets/Scripts/Utility/Tags.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#61 Fix UI Camera stutter
  Assets/Scripts/UI/UICamera.cs
Labels: bug

#62 Unsubscribe network handlers when object is destroyed
  Assets/Scripts/Networking/NetworkHandlers.cs
Labels: enhancement

#76 Add IP address regex validation
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#74 Make candle flame always face camera
  Assets/Prefabs/Environment/Lanterns/Latern5.prefab
  Assets/Prefabs/Environment/Lanterns/candlestick.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Components/CameraFacing.cs
  Assets/Scripts/Components/CameraFacing.cs.meta
Labels: enhancement

#77 Fix UI scaling
  Assets/Scenes/SampleScene.unity
Labels: bug

#78 Handle exception when hosting
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#80 Add game tutorial
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
  Assets/UI/scroll-34696.png
  Assets/UI/scroll-34696.png.meta
Labels: feature

#81 Go to main menu when a host or client disconnects
  Assets/Scripts/Networking/NetworkManagerHnefatafl.cs
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#82 Add waitingUI
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#85 Add game tutorial option in main menu
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UI/Menus.cs
Labels: enhancement

#86 Rename main menu buttons
  Assets/Scenes/SampleScene.unity
Labels: enhancement

#87 Allow client input on join
  Assets/Scripts/UI/Menus.cs
Labels: bug

#88 Fix button positioning
  Assets/Scenes/SampleScene.unity
Labels: bug
